package com.programacion2.cine.igu;

import com.programacion2.cine.logica.ControladoraLogica;
import com.programacion2.cine.logica.DTOPelicula;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DavidRoco
 */

public class AdministrarPeliculas extends javax.swing.JFrame {
    ControladoraLogica controla = new ControladoraLogica();
    private static AdministrarPeliculas instance = null;
    /**
     * Creates new form MenuInicial
     */
    public AdministrarPeliculas() {
        initComponents();
        cargarTabla();
    }
    
    public static AdministrarPeliculas getInstance() {
        if (instance == null) {
            instance = new AdministrarPeliculas();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jLabelAdministrarPeliculas = new javax.swing.JLabel();
        jLabelSistemaCineProgramacion2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBajaPelicula = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPelicula = new javax.swing.JTable();
        jLabelDescuentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnSalir.setText("Volver al Menú Inicial");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabelAdministrarPeliculas.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabelAdministrarPeliculas.setText("Administrar Películas");

        jLabelSistemaCineProgramacion2.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabelSistemaCineProgramacion2.setText("Sistema Cine Programación 2");

        btnAgregar.setText("Agregar Película");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Película");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBajaPelicula.setText("Baja Película");
        btnBajaPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaPeliculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBajaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnBajaPelicula)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        tablaPelicula.setBorder(new javax.swing.border.MatteBorder(null));
        tablaPelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaPelicula);

        jLabelDescuentos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDescuentos.setText("Películas");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelAdministrarPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1091, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSistemaCineProgramacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabelSistemaCineProgramacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAdministrarPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelDescuentos)
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();       
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        AgregarPelicula pantallaAgregarPelicula = AgregarPelicula.getInstance();
        pantallaAgregarPelicula.setVisible(true);
        pantallaAgregarPelicula.setLocationRelativeTo(null);
        cargarTabla();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       cargarTabla();
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       cargarTabla();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //hay mas de una fila en la tabla
        if (tablaPelicula.getRowCount() > 0) {
            //hay por lo menos una selección
            if (tablaPelicula.getSelectedRow() != -1) {
                //optengo la id a borrar
                int idPelicula = Integer.parseInt(String.valueOf(tablaPelicula.getValueAt(tablaPelicula.getSelectedRow(), 0)));
                
                controla.borrarPelicula(idPelicula);
                
                mostrarMensajes("Se Eliminó correctamente La Pelicula","Info", "Eliminación Exitosa");
            }
            else{
                mostrarMensajes("No Seleccionó ningún Registro","Error", "No se elimnó el registro");
            }
        }
        else{
            mostrarMensajes("No hay registros para eliminar","Error", "No se elimnó el registro");
        }
        cargarTabla();                                          
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      //hay mas de una fila en la tabla
        if (tablaPelicula.getRowCount() > 0) {
            //hay por lo menos una selección
            if (tablaPelicula.getSelectedRow() != -1) {
                //optengo la id a borrar
                int idPelicula = Integer.parseInt(String.valueOf(tablaPelicula.getValueAt(tablaPelicula.getSelectedRow(), 0)));
                
                EditarPelicula pantallaEditPelicula = new EditarPelicula(idPelicula);
                pantallaEditPelicula.setVisible(true);
                pantallaEditPelicula.setLocationRelativeTo(null);
              
            
            }
            else{
                mostrarMensajes("No Seleccionó ningún registro","Error", "No se Editó el registro");
            }
        }
        else{
            mostrarMensajes("No hay registros para eliminar","Error", "No se Editó el registro");
        }
        cargarTabla();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBajaPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaPeliculaActionPerformed
         //hay mas de una fila en la tabla
        if (tablaPelicula.getRowCount() > 0) {
            //hay por lo menos una selección
            if (tablaPelicula.getSelectedRow() != -1) {
                //optengo la id a borrar
                int idPelicula = Integer.parseInt(String.valueOf(tablaPelicula.getValueAt(tablaPelicula.getSelectedRow(), 0)));
                
                String fechaBaja = String.valueOf(tablaPelicula.getValueAt(tablaPelicula.getSelectedRow(), 7));
                System.out.println(fechaBaja);
                
                if ("null".equals(fechaBaja)){                
                    controla.bajaPelicula(idPelicula);
                    
                } else {
                    mostrarMensajes("La Pelicula Ya tiene fecha de baja","Error", "No se Editó el registro");
                }
                
            }
            else{
                mostrarMensajes("No Seleccionó ningún Registro","Error", "No se Editó el registro");
            }
        }
        else{
            mostrarMensajes("No hay registros para eliminar","Error", "No se Editó el registro");
        }
        cargarTabla();
                                            
    }//GEN-LAST:event_btnBajaPeliculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBajaPelicula;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabelAdministrarPeliculas;
    private javax.swing.JLabel jLabelDescuentos;
    private javax.swing.JLabel jLabelSistemaCineProgramacion2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPelicula;
    // End of variables declaration//GEN-END:variables

    public void cargarTabla() {
          
        DefaultTableModel tabla = new DefaultTableModel(){
            
            //filas y columnas no editables
            @Override
            public boolean isCellEditable (int row, int column){
                return false;
            }
        };
        //establecer nombre y columnas
        
        String titulos[] = {"NRO-Película", "Título", "Director", "Elenco", "Duración", "Género", "Fecha Alta", "Fecha Baja"};
        tabla.setColumnIdentifiers(titulos);
        
        
        //carga de los datos desde la base de datos
        List <DTOPelicula> listaPeliculas = controla.traerPeliculas();
        
        
        //recorrer la lista y mostrar cada uno de llos elementos en la tabla
        
        if (listaPeliculas != null){
            for (DTOPelicula dtoPelicula : listaPeliculas){
                if (dtoPelicula.getFechaBaja() == null){
                   Object[] objeto = {dtoPelicula.getIdPelicula(), dtoPelicula.getTitulo(),dtoPelicula.getDirector(), dtoPelicula.getElenco(), dtoPelicula.getDuracion(), dtoPelicula.getGenero(), new SimpleDateFormat("dd-MM-yyyy").format(dtoPelicula.getFechaAlta()), dtoPelicula.getFechaBaja()}; 
                   tabla.addRow(objeto);
                }else{
                   Object[] objeto1 = {dtoPelicula.getIdPelicula(), dtoPelicula.getTitulo(),dtoPelicula.getDirector(), dtoPelicula.getElenco(), dtoPelicula.getDuracion(), dtoPelicula.getGenero(), new SimpleDateFormat("dd-MM-yyyy").format(dtoPelicula.getFechaAlta()), new SimpleDateFormat("dd-MM-yyyy").format(dtoPelicula.getFechaBaja())};
                   tabla.addRow(objeto1);
                }
                
            }
        }
        tablaPelicula.setModel(tabla);

    }
    
    
    public void mostrarMensajes(String mensaje, String tipo,String titulo){
        JOptionPane optionPane = new JOptionPane(mensaje);
        if (tipo.equals("Info")){
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
            
        }
        else if (tipo.equals("Error")){
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog = optionPane.createDialog(titulo);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);  
    }
}
