package com.programacion2.cine.igu;

import com.programacion2.cine.logica.ControladoraLogica;
import com.programacion2.cine.logica.DTOFuncion;
import com.programacion2.cine.logica.DTOPelicula;
import com.programacion2.cine.logica.ExpertoABMFuncion;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DavidRoco
 */

public class AdministrarFunciones extends javax.swing.JFrame {
    ControladoraLogica controla = new ControladoraLogica();
    private static AdministrarFunciones instance = null;
    ExpertoABMFuncion experto = new ExpertoABMFuncion();
   
    /**
     * Creates new form MenuInicial
     */
    public AdministrarFunciones() {
        initComponents();
        cargarTabla();
    }
    
    public static AdministrarFunciones getInstance() {
        if (instance == null) {
            instance = new AdministrarFunciones();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelAdministrarPeliculas = new javax.swing.JLabel();
        jLabelSistemaCineProgramacion2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCrearFuncion = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCambiarEstadoFuncion = new javax.swing.JButton();
        btnVerEntradas = new javax.swing.JButton();
        btnCambiarFecha = new javax.swing.JButton();
        btnCambiarHorario = new javax.swing.JButton();
        btnCambiarSala = new javax.swing.JButton();
        btnCambiarPelicula = new javax.swing.JButton();
        btnCambiarPrecioEntrada = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFunciones = new javax.swing.JTable();
        jLabelDescuentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelAdministrarPeliculas.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabelAdministrarPeliculas.setText("Administrar Funciones");

        jLabelSistemaCineProgramacion2.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabelSistemaCineProgramacion2.setText("Sistema Cine Programación 2");

        btnCrearFuncion.setText("Crear Función");
        btnCrearFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearFuncionActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Función");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCambiarEstadoFuncion.setText("Cambiar Estado");
        btnCambiarEstadoFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEstadoFuncionActionPerformed(evt);
            }
        });

        btnVerEntradas.setText("Ver Entradas");
        btnVerEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEntradasActionPerformed(evt);
            }
        });

        btnCambiarFecha.setText("Cambiar Fecha");
        btnCambiarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarFechaActionPerformed(evt);
            }
        });

        btnCambiarHorario.setText("Cambiar Horario");
        btnCambiarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarHorarioActionPerformed(evt);
            }
        });

        btnCambiarSala.setText("Cambiar Sala");
        btnCambiarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarSalaActionPerformed(evt);
            }
        });

        btnCambiarPelicula.setText("Cambiar Película");
        btnCambiarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarPeliculaActionPerformed(evt);
            }
        });

        btnCambiarPrecioEntrada.setText("Camb Precio Entrada");
        btnCambiarPrecioEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarPrecioEntradaActionPerformed(evt);
            }
        });

        btnSalir.setText("Volver al Menú Inicial");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarEstadoFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarPrecioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnCrearFuncion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiarFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiarHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiarSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiarPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiarEstadoFuncion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiarPrecioEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerEntradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        tablaFunciones.setBorder(new javax.swing.border.MatteBorder(null));
        tablaFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaFunciones);

        jLabelDescuentos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDescuentos.setText("Funciones");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302)
                .addComponent(jLabelAdministrarPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jLabelSistemaCineProgramacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1091, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelSistemaCineProgramacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDescuentos))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAdministrarPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       cargarTabla();
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       cargarTabla();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnCambiarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarPeliculaActionPerformed
        //hay mas de una fila en la tabla
        if (tablaFunciones.getRowCount() > 0) {
            //hay por lo menos una selección
            if (tablaFunciones.getSelectedRow() != -1) {
                int idFuncion = Integer.parseInt(String.valueOf(tablaFunciones.getValueAt(tablaFunciones.getSelectedRow(), 0)));

                CambiarPeliculaFuncion pantallaCambPelicula = new CambiarPeliculaFuncion(idFuncion);
                pantallaCambPelicula.setVisible(true);
                pantallaCambPelicula.setLocationRelativeTo(null);

            }
            else{
                mostrarMensajes("No Seleccionó ningún registro","Error", "No se Editó el registro");
            }
        }
        else{
            mostrarMensajes("No hay registros","Error", "No se Editó el registro");
        }
        cargarTabla();
    }//GEN-LAST:event_btnCambiarPeliculaActionPerformed

    private void btnCambiarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarSalaActionPerformed
      
       //hay mas de una fila en la tabla
        if (tablaFunciones.getRowCount() > 0) {
            //hay por lo menos una selección
            if (tablaFunciones.getSelectedRow() != -1) {
                int idFuncion = Integer.parseInt(String.valueOf(tablaFunciones.getValueAt(tablaFunciones.getSelectedRow(), 0)));

                CambiarSalaFuncion pantallaCambSala = new CambiarSalaFuncion(idFuncion);
                pantallaCambSala.setVisible(true);
                pantallaCambSala.setLocationRelativeTo(null);

            }
            else{
                mostrarMensajes("No Seleccionó ningún registro","Error", "No se Editó el registro");
            }
        }
        else{
            mostrarMensajes("No hay registros","Error", "No se Editó el registro");
        }
        cargarTabla();
                                                     
        
              
              
    }//GEN-LAST:event_btnCambiarSalaActionPerformed

    private void btnCambiarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarHorarioActionPerformed
       
       if (tablaFunciones.getRowCount() > 0) {
            //hay por lo menos una selección
            if (tablaFunciones.getSelectedRow() != -1) {
                int idFuncion = Integer.parseInt(String.valueOf(tablaFunciones.getValueAt(tablaFunciones.getSelectedRow(), 0)));

                CambiarHorarioFuncion pantallaCambHorario = new CambiarHorarioFuncion(idFuncion);
                pantallaCambHorario.setVisible(true);
                pantallaCambHorario.setLocationRelativeTo(null);

            }
            else{
                mostrarMensajes("No Seleccionó ningún registro","Error", "No se Editó el registro");
            }
        }
        else{
            mostrarMensajes("No hay registros","Error", "No se Editó el registro");
        }
        cargarTabla();
       
    }//GEN-LAST:event_btnCambiarHorarioActionPerformed

    private void btnCambiarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarFechaActionPerformed
                                
            //hay mas de una fila en la tabla
        if (tablaFunciones.getRowCount() > 0) {
            //hay por lo menos una selección
            if (tablaFunciones.getSelectedRow() != -1) {
                int idFuncion = Integer.parseInt(String.valueOf(tablaFunciones.getValueAt(tablaFunciones.getSelectedRow(), 0)));

                CambiarFechaFuncion pantallaCambFecha = new CambiarFechaFuncion(idFuncion);
                pantallaCambFecha.setVisible(true);
                pantallaCambFecha.setLocationRelativeTo(null);

            }
            else{
                mostrarMensajes("No Seleccionó ningún registro","Error", "No se Editó el registro");
            }
        }
        else{
            mostrarMensajes("No hay registros","Error", "No se Editó el registro");
        }
        cargarTabla();
                                                     
        
              
                
    }//GEN-LAST:event_btnCambiarFechaActionPerformed

    private void btnVerEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEntradasActionPerformed
        //hay mas de una fila en la tabla
        if (tablaFunciones.getRowCount() > 0) {
            //hay por lo menos una selección
            if (tablaFunciones.getSelectedRow() != -1) {
                //optengo la id a borrar
                int idFuncion = Integer.parseInt(String.valueOf(tablaFunciones.getValueAt(tablaFunciones.getSelectedRow(), 0)));

                VerEntradasFuncion pantallaVerEntradas = new VerEntradasFuncion(idFuncion);
                pantallaVerEntradas.setVisible(true);
                pantallaVerEntradas.setLocationRelativeTo(null);

            }
            else{
                mostrarMensajes("No Seleccionó ningún Registro","Error", "No se Editó el registro");
            }
        }
        else{
            mostrarMensajes("No hay registros para Mostrar","Error", "No se Editó el registro");
        }
        cargarTabla();

                                          
        
    }//GEN-LAST:event_btnVerEntradasActionPerformed

    private void btnCambiarEstadoFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoFuncionActionPerformed
        //hay mas de una fila en la tabla
        if (tablaFunciones.getRowCount() > 0) {
            //hay por lo menos una selección
            if (tablaFunciones.getSelectedRow() != -1) {
                //optengo la id a borrar
                int idFuncion = Integer.parseInt(String.valueOf(tablaFunciones.getValueAt(tablaFunciones.getSelectedRow(), 0)));

                CambiarEstadoFuncion pantallaCambEstado = new CambiarEstadoFuncion(idFuncion);
                pantallaCambEstado.setVisible(true);
                pantallaCambEstado.setLocationRelativeTo(null);

            }
            else{
                mostrarMensajes("No Seleccionó ningún Registro","Error", "No se Editó el registro");
            }
        }
        else{
            mostrarMensajes("No hay registros para eliminar","Error", "No se Editó el registro");
        }
        cargarTabla();

    }//GEN-LAST:event_btnCambiarEstadoFuncionActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //hay mas de una fila en la tabla
        if (tablaFunciones.getRowCount() > 0) {
            //hay por lo menos una selección
            if (tablaFunciones.getSelectedRow() != -1) {
                //optengo la id a borrar
                int idFuncion = Integer.parseInt(String.valueOf(tablaFunciones.getValueAt(tablaFunciones.getSelectedRow(), 0)));

                experto.borrarFuncion(idFuncion);

                mostrarMensajes("Se Eliminó correctamente La Función","Info", "Eliminación Exitosa");
            }
            else{
                mostrarMensajes("No Seleccionó ningún Registro","Error", "No se elimnó el registro");
            }
        }
        else{
            mostrarMensajes("No hay registros para eliminar","Error", "No se elimnó el registro");
        }
        cargarTabla();

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCrearFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearFuncionActionPerformed
        AgregarFuncion pantallaCrearFuncion = AgregarFuncion.getInstance();
        pantallaCrearFuncion.setVisible(true);
        pantallaCrearFuncion.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCrearFuncionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        MenuSettingParametros menuSetting = MenuSettingParametros.getInstance(); 
        menuSetting.setVisible(true);
        menuSetting.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCambiarPrecioEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarPrecioEntradaActionPerformed
        
                                
            //hay mas de una fila en la tabla
        if (tablaFunciones.getRowCount() > 0) {
            //hay por lo menos una selección
            if (tablaFunciones.getSelectedRow() != -1) {
                int idFuncion = Integer.parseInt(String.valueOf(tablaFunciones.getValueAt(tablaFunciones.getSelectedRow(), 0)));

                CambiarPrecioEntradaFuncion pantallaCambPrecioEntrada = new CambiarPrecioEntradaFuncion(idFuncion);
                pantallaCambPrecioEntrada.setVisible(true);
                pantallaCambPrecioEntrada.setLocationRelativeTo(null);

            }
            else{
                mostrarMensajes("No Seleccionó ningún registro","Error", "No se Editó el registro");
            }
        }
        else{
            mostrarMensajes("No hay registros","Error", "No se Editó el registro");
        }
        cargarTabla();
                                     
                
    }//GEN-LAST:event_btnCambiarPrecioEntradaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarEstadoFuncion;
    private javax.swing.JButton btnCambiarFecha;
    private javax.swing.JButton btnCambiarHorario;
    private javax.swing.JButton btnCambiarPelicula;
    private javax.swing.JButton btnCambiarPrecioEntrada;
    private javax.swing.JButton btnCambiarSala;
    private javax.swing.JButton btnCrearFuncion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerEntradas;
    private javax.swing.JLabel jLabelAdministrarPeliculas;
    private javax.swing.JLabel jLabelDescuentos;
    private javax.swing.JLabel jLabelSistemaCineProgramacion2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFunciones;
    // End of variables declaration//GEN-END:variables

    public void cargarTabla() {
          
        DefaultTableModel tabla = new DefaultTableModel(){
            
            //filas y columnas no editables
            @Override
            public boolean isCellEditable (int row, int column){
                return false;
            }
        };
        //establecer nombre y columnas
        
        String titulos[] = {"ID-Función", "Fecha", "Horario", "Sala", "Película", "Estado", "Precio Entrada"};
        tabla.setColumnIdentifiers(titulos);
        
        
        //carga de los datos desde la base de datos
        List <DTOFuncion> listaFunciones = experto.traerFunciones();
        
        
        //recorrer la lista y mostrar cada uno de llos elementos en la tabla
        
        if (listaFunciones != null){
            for (DTOFuncion dtoFuncion : listaFunciones){
                Object[] objeto = {dtoFuncion.getIdFuncion(), new SimpleDateFormat("dd-MM-yyyy").format(dtoFuncion.getFecha()),dtoFuncion.getHorario(),dtoFuncion.getNombreSala(),dtoFuncion.getNombrePelicula(), dtoFuncion.getNombreEstado(), dtoFuncion.getPrecioEntradas()}; 
                   tabla.addRow(objeto);
               
            }
        }
        tablaFunciones.setModel(tabla);

    }
    
    
    public void mostrarMensajes(String mensaje, String tipo,String titulo){
        JOptionPane optionPane = new JOptionPane(mensaje);
        if (tipo.equals("Info")){
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
            
        }
        else if (tipo.equals("Error")){
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog = optionPane.createDialog(titulo);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);  
    }
}
